services:
  semaphore:
    container_name: semaphore
    restart: unless-stopped
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: CHANGEME
      SEMAPHORE_DB_HOST: srv-docker-2.server.io
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: CHANGEME
      SEMAPHORE_ADMIN_NAME: Kajeepan Kandeepan
      SEMAPHORE_ADMIN_EMAIL: kajeepan.kandeepan@gmail.com
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: CHANGEME
      SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes'
    labels:
      - traefik.enable=true
      - traefik.http.routers.semaphore.entrypoints=websecure
      - traefik.http.routers.semaphore.rule=Host(`semaphore.srv-docker-1.server.io`)
      - traefik.http.routers.semaphore.tls=true
      - traefik.http.services.semaphore.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
