vyos_hostname: "vyos"
vyos_timezone: Europe/Berlin
# chore: update the latest image URL
# images: https://github.com/vyos/vyos-rolling-nightly-builds/releases/
vyos_latest_image_url: https://github.com/vyos/vyos-nightly-build/releases/download/1.5-rolling-202411270007/vyos-1.5-rolling-202411270007-generic-amd64.iso

vyos_system:
  is_vm: true

vyos_interfaces:
  - name: eth1
    ipv4: "10.10.0.1/24"
    ipv6: "fd10::1/64"
    description: "MGMT"
  - name: eth2
    ipv4: "10.30.0.1/24"
    ipv6: "fd30::1/64"
    description: "PROD"
  - name: eth3
    ipv4: "10.40.0.1/24"
    ipv6: "fd40::1/64"
    description: "STAG"
  - name: eth4
    ipv4: "10.50.0.1/24"
    ipv6: "fd50::1/64"
    description: "STOR"
  - name: eth5
    ipv4: "172.16.0.1/24"
    ipv6: "fd64:100::1/64"
    description: "DMZ"

vyos_dhcpv4_configs:
  - network_name: "MGMT"
    subnet: "10.10.0.0/24"
    subnet_id: "1"
    ranges:
      - id: "0"
        start: "10.10.0.50"
        end: "10.10.0.250"
    domain_name: "server.home"
    default_router: "10.10.0.1"
    dns_server: "10.10.0.1"
    lease_time: "86400"
    tftp_server_name: "10.10.0.1"
    static_mappings:
      # Management
      - mac: "BC:24:11:85:85:9E"
        ip: "10.10.0.2"
        description: "mgmt"
      # Core Cluster
      - mac: "BC:24:11:8D:F4:67"
        ip: "10.10.0.3"
        description: "control1-core"
      - mac: "BC:24:11:D7:C0:1A"
        ip: "10.10.0.4"
        description: "worker1-core"
      - mac: "BC:24:11:02:9B:4D"
        ip: "10.10.0.5"
        description: "worker2-core"
      - mac: "BC:24:11:FA:90:32"
        ip: "10.10.0.6"
        description: "worker3-core"
      # Bastion
      - mac: "BC:24:11:B7:42:81"
        ip: "10.10.0.20"
        description: "bastion"
  - network_name: "PROD"
    subnet: "10.30.0.0/24"
    subnet_id: "2"
    ranges:
      - id: "0"
        start: "10.30.0.50"
        end: "10.30.0.250"
    domain_name: "server.home"
    default_router: "10.30.0.1"
    dns_server: "10.30.0.1"
    lease_time: "86400"
    tftp_server_name: "10.30.0.1"
    static_mappings:
      # Control Nodes
      - mac: "BC:24:11:BF:98:DA"
        ip: "10.30.0.2"
        description: "control1-prod"
      - mac: "BC:24:11:0F:61:0A"
        ip: "10.30.0.3"
        description: "control2-prod"
      - mac: "BC:24:11:05:88:0A"
        ip: "10.30.0.4"
        description: "control3-prod"
      # Worker Nodes
      - mac: "BC:24:11:DF:78:1D"
        ip: "10.30.0.7"
        description: "worker1-prod"
      - mac: "BC:24:11:A9:CA:D7"
        ip: "10.30.0.8"
        description: "worker2-prod"
      - mac: "BC:24:11:2A:76:E6"
        ip: "10.30.0.9"
        description: "worker3-prod"
      # Docker
      - mac: "BC:24:11:46:5F:68"
        ip: "10.30.0.20"
        description: "docker"
  - network_name: "STAG"
    subnet: "10.40.0.0/24"
    subnet_id: "3"
    ranges:
      - id: "0"
        start: "10.40.0.50"
        end: "10.40.0.250"
    domain_name: "server.home"
    default_router: "10.40.0.1"
    dns_server: "10.40.0.1"
    lease_time: "86400"
    tftp_server_name: "10.40.0.1"
    static_mappings:
      # Single Node
      - mac: "BC:24:11:E6:F7:66"
        ip: "10.40.0.2"
        description: "control1-stag"
      - mac: "BC:24:11:9F:B1:22"
        ip: "10.40.0.3"
        description: "worker1-stag"
  - network_name: "STOR"
    subnet: "10.50.0.0/24"
    subnet_id: "4"
    ranges:
      - id: "0"
        start: "10.50.0.50"
        end: "10.50.0.250"
    domain_name: "server.home"
    default_router: "10.50.0.1"
    dns_server: "10.50.0.1"
    lease_time: "86400"
    tftp_server_name: "10.50.0.1"
    static_mappings:
      - mac: "BC:24:11:76:48:09"
        ip: "10.50.0.2"
        description: "storage1"
  - network_name: "DMZ"
    subnet: "172.16.0.0/24"
    subnet_id: "5"
    ranges:
      - id: "0"
        start: "172.16.0.50"
        end: "172.16.0.250"
    domain_name: "server.home"
    default_router: "172.16.0.1"
    dns_server: "8.8.8.8" # Google DNS
    lease_time: "86400"
    static_mappings:
      - mac: "BC:24:11:30:26:A8"
        ip: "172.16.0.10"
        description: "dmz"

vyos_dhcpv6_configs:
  - network_name: "MGMT"
    subnet: "fd10::/64"
    subnet_id: "1"
    ranges:
      - id: "0"
        start: "fd10::100"
        end: "fd10::200"
    domain_name: "server.home"
    name_server: "fd10::1"
  - network_name: "PROD"
    subnet: "fd30::/64"
    subnet_id: "2"
    ranges:
      - id: "0"
        start: "fd30::100"
        end: "fd30::200"
    domain_name: "server.home"
    name_server: "fd30::1"
  - network_name: "STAG"
    subnet: "fd40::/64"
    subnet_id: "3"
    ranges:
      - id: "0"
        start: "fd40::100"
        end: "fd40::200"
    domain_name: "server.home"
    name_server: "fd40::1"
  - network_name: "STOR"
    subnet: "fd50::/64"
    subnet_id: "4"
    ranges:
      - id: "0"
        start: "fd50::100"
        end: "fd50::200"
    domain_name: "server.home"
    name_server: "fd50::1"
  - network_name: "DMZ"
    subnet: "fd64:100::/64"
    subnet_id: "5"
    ranges:
      - id: "0"
        start: "fd64:100::100"
        end: "fd64:100::200"
    domain_name: "server.home"
    name_server: "2001:4860:4860::8888" # Google DNS

vyos_dns_configs:
  search_domain: "server.home"
  upstream_dns:
    - "8.8.8.8"
  allow_from:
    - "10.0.0.0/8"
    - "fc00::/7"
  listen_addresses:
    - "10.10.0.1"
    - "10.30.0.1"
    - "10.40.0.1"
    - "10.50.0.1"
    - "fd10::1"
    - "fd30::1"
    - "fd40::1"
    - "fd50::1"
  records:
    - domain: "server.home"
      type: "A"
      name: "@"
      address: "10.10.0.1"
    # Core Cluster Load Balancer
    - domain: "core.infra.server.home"
      type: "A"
      name: "any"
      address: "10.10.0.10"
    - domain: "core.infra.server.home"
      type: "A"
      name: "@"
      address: "10.10.0.3"
    # MGMT Cluster
    - domain: "mgmt.infra.server.home"
      type: "A"
      name: "@"
      address: "10.10.0.2"
    # Bastion
    - domain: "bastion.infra.server.home"
      type: "A"
      name: "@"
      address: "10.10.0.4"
    # Production Cluster
    - domain: "prod.server.home"
      type: "A"
      name: "@"
      address: "10.30.0.2"
    - domain: "prod.server.home"
      type: "A"
      name: "@"
      address: "10.30.0.3"
    - domain: "prod.server.home"
      type: "A"
      name: "@"
      address: "10.30.0.4"
    - domain: "prod.server.home"
      type: "A"
      name: "any"
      address: "10.30.0.10"
    # Docker
    - domain: "app.server.home"
      type: "A"
      name: "@"
      address: "10.30.0.20"
    - domain: "app.server.home"
      type: "A"
      name: "any"
      address: "10.30.0.20"
    # Staging Cluster
    - domain: "staging.server.home"
      type: "A"
      name: "@"
      address: "10.40.0.2"
    - domain: "staging.server.home"
      type: "A"
      name: "any"
      address: "10.40.0.10"
    # S3 Load Balancer
    - domain: "s3.infra.server.home"
      type: "A"
      name: "@"
      address: "10.50.0.2"

vyos_nat_configs:
  - outbound_interface: eth0
    source: "10.10.0.0/24"
    translation: "masquerade"
  - outbound_interface: eth0
    source: "10.30.0.0/24"
    translation: "masquerade"
  - outbound_interface: eth0
    source: "10.40.0.0/24"
    translation: "masquerade"
  - outbound_interface: eth0
    source: "10.50.0.0/24"
    translation: "masquerade"
  - outbound_interface: eth0
    source: "172.16.0.0/24"
    translation: "masquerade"

vyos_ssh_config:
  key_type: "ssh-ed25519"
  pub_key_path: "files/homelab.pub"
  disable_password_authentication: false

vyos_wireguard:
  # The name of the wireguard interface
  interface: wg01

  # The name of the peer
  peer_name: Homelab
  description: VPN

  # interface ip
  interface_ip: "10.100.0.1/30"

  # The port we listen on
  listen_port: "51820"

  # The allowed ips for the peer
  allowed_ips:
    - "10.100.0.2/32"

  # The public key from the client
  public_key: "n1EO5Qs9humFy8bsaueupnL8bcH01MoQEbQPeQdNK10="

  keepalive_duration: "15"

  # Wether new pre-shred and public keys should be configured
  refresh_keys: false

# TFTP Server Configuration
vyos_tftp:
  enabled: true
  directory: "/config/tftpboot"
  address: "10.10.0.1"
  allow_upload: true
