vyos_hostname: "vyos"
vyos_timezone: Europe/Berlin
# chore: update the latest image URL
# images: https://github.com/vyos/vyos-rolling-nightly-builds/releases/
vyos_latest_image_url: https://github.com/vyos/vyos-rolling-nightly-builds/releases/download/1.5-rolling-202406280020/vyos-1.5-rolling-202406280020-amd64.iso

vyos_interfaces:
  - name: eth1
    ipv4: "10.0.0.1/16"
    ipv6: "fd00:0:0:1::1/64"
    description: "LAN1"
  - name: eth2
    ipv4: "10.1.0.1/16"
    ipv6: "fd00:0:0:2::1/64"
    description: "LAN2"
  - name: eth3
    description: "DMZ"
    ipv4: "172.16.1.1/24"
    ipv6: "fd00::1/64"

vyos_dhcpv4_configs:
  - network_name: "LAN1"
    subnet: "10.0.0.0/16"
    ranges:
      - id: "0"
        start: "10.0.255.10"
        end: "10.0.255.245"
    domain_name: "server.home"
    default_router: "10.0.0.1"
    dns_server: "10.0.0.1"
    subnet_id: "1"
    lease_time: "86400"
    tftp_server_name: "10.0.0.1"
    static_mappings:
      - mac: "BC:24:11:48:6D:FB"
        ip: "10.0.0.200"
        description: "test-1"
      - mac: "BC:24:11:18:D5:A3"
        ip: "10.0.2.0"
        description: "srv-rancher"
      - mac: "BC:24:11:89:6D:82"
        ip: "10.0.3.0"
        description: "node1"
      - mac: "BC:24:11:7F:76:CA"
        ip: "10.0.3.1"
        description: "node2"
      - mac: "BC:24:11:64:24:C8"
        ip: "10.0.3.2"
        description: "node3"
      - mac: "BC:24:11:74:E9:90"
        ip: "10.0.3.4"
        description: "node4"
      - mac: "BC:24:11:B9:51:DE"
        ip: "10.0.3.5"
        description: "node5"
      - mac: "BC:24:11:6E:C7:2D"
        ip: "10.0.3.6"
        description: "node6"
      - mac: "BC:24:11:E2:2A:C4"
        ip: "10.0.3.7"
        description: "node7"
      - mac: "BC:24:11:3D:C1:6A"
        ip: "10.0.3.8"
        description: "node8"
      - mac: "BC:24:11:DE:EA:85"
        ip: "10.0.4.0"
        description: "srv-docker-1"
      - mac: "BC:24:11:F1:41:6A"
        ip: "10.0.4.10"
        description: "srv-kasm"
  - network_name: "LAN2"
    subnet: "10.1.0.0/16"
    ranges:
      - id: "0"
        start: "10.1.255.10"
        end: "10.1.255.245"
    domain_name: "server.home"
    default_router: "10.1.0.1"
    dns_server: "10.1.0.1"
    subnet_id: "2"
    lease_time: "86400"
    static_mappings:
      - mac: "BC:24:11:AE:66:AC"
        ip: "10.1.0.200"
        description: "test-2"
      - mac: "BC:24:11:C8:4C:F9"
        ip: "10.1.1.10"
        description: "rke2-node-1"
      - mac: "BC:24:11:C4:E6:22"
        ip: "10.1.1.11"
        description: "rke2-node-2"
      - mac: "BC:24:11:38:DE:77"
        ip: "10.1.1.12"
        description: "rke2-node-3"
  - network_name: "DMZ"
    subnet: "172.16.1.0/24"
    ranges:
      - id: "0"
        start: "172.16.1.10"
        end: "172.16.1.245"
    domain_name: "server.home"
    default_router: "172.16.1.1"
    dns_server: "8.8.8.8" # Google DNS
    subnet_id: "3"
    lease_time: "86400"
    static_mappings:
      - mac: "BC:24:11:39:34:5B"
        ip: "172.16.1.10"
        description: "test-3"

vyos_dhcpv6_configs:
  - network_name: "LAN1"
    subnet: "fd00:0:0:1::/64"
    subnet_id: "1"
    ranges:
      - id: "0"
        start: "fd00:0:0:1::1"
        end: "fd00:0:0:1::ffff"
    domain_name: "server.home"
    name_server: "fd00:0:0:1::1"
  - network_name: "LAN2"
    subnet: "fd00:0:0:2::/64"
    subnet_id: "2"
    ranges:
      - id: "0"
        start: "fd00:0:0:2::1"
        end: "fd00:0:0:2::ffff"
    domain_name: "server.home"
    name_server: "fd00:0:0:2::1"
  - network_name: "DMZ"
    subnet: "fd00::/64"
    subnet_id: "3"
    ranges:
      - id: "0"
        start: "fd00::1:0"
        end: "fd00::1:ffff"
    domain_name: "server.home"
    name_server: "2001:4860:4860::8888" # Google DNS

vyos_dns_configs:
  search_domain: "server.home"
  upstream_dns:
    - "8.8.8.8"
  allow_from:
    - "10.0.0.0/8"
    - "fd00::/8"
    - "10.100.0.0/30"
  listen_addresses:
    - "10.0.0.1"
    - "10.1.0.1"
    - "fd00:0:0:1::1"
  records:
    - domain: "server.home"
      type: "A"
      name: "@"
      address: "10.0.0.1"
    - domain: "prod.server.home"
      type: "A"
      name: "any"
      address: "10.0.255.1"
    - domain: "staging.server.home"
      type: "A"
      name: "any"
      address: "10.1.255.1"
    - domain: "srv-core.server.home"
      type: "A"
      name: "any"
      address: "10.0.4.0"
    - domain: "srv-core.server.home"
      type: "A"
      name: "@"
      address: "10.0.4.0"
    - domain: "srv-kasm.server.home"
      type: "A"
      name: "@"
      address: "10.0.4.10"
    - domain: "srv-rancher.server.home"
      type: "A"
      name: "@"
      address: "10.0.2.0"

vyos_nat_configs:
  - outbound_interface: eth0
    source: "10.0.0.0/16"
    translation: "masquerade"
  - outbound_interface: eth0
    source: "10.1.0.0/16"
    translation: "masquerade"
  - outbound_interface: eth0
    source: "172.16.1.0/24"
    translation: "masquerade"

vyos_ssh_config:
  key_type: "ssh-ed25519"
  pub_key_path: "files/homelab.pub"
  disable_password_authentication: false

vyos_wireguard:
  # The name of the wireguard interface
  interface: wg01

  # The name of the peer
  peer_name: Homelab
  description: VPN

  # interface ip
  interface_ip: "10.100.0.1/30"

  # The port we listen on
  listen_port: "51820"

  # The allowed ips for the peer
  allowed_ips:
    - "10.100.0.2/32"

  # The public key from the client
  public_key: "n1EO5Qs9humFy8bsaueupnL8bcH01MoQEbQPeQdNK10="

  keepalive_duration: "15"

  # Wether new pre-shred and public keys should be configured
  refresh_keys: true

# TFTP Server Configuration
vyos_tftp:
  enabled: true
  directory: "/config/tftpboot"
  address: "10.0.0.1"
  allow_upload: true
