apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Monitoring stack
  - kube-prometheus-stack/cert.yaml
  - kube-prometheus-stack/release.yaml
  - kube-prometheus-stack/repository.yaml

  # Endpoint monitoring
  - blackbox/release.yaml

  # Grafana Dashboards
  - dashboards/istio.yaml
  - dashboards/kube-metrics.yaml
