---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/metrics-server/
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: "3.x.x"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: metrics-server
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    apiService:
      insecureSkipTLSVerify: true
    args:
      - --kubelet-insecure-tls