---
apiVersion: v1
kind: Namespace
metadata:
  name: portainer
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 30m
  url: https://portainer.github.io/k8s/
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m
  chart:
    spec:
      chart: portainer
      version: 1.0.49
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: portainer
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: 
    ingress:
      annotations: {}
      enabled: true
      hosts:
        - host: portainer.srv-k8s.server.io
          paths:
            - path: /
              pathType: Prefix
      ingressClassName: 'traefik'
      tls:
        - hosts:
          - portainer.srv-k8s.server.io
          secretName: portainer-tls
    persistence:
      annotations: {}
      enabled: true
      existingClaim: null
      size: 2Gi
      storageClass: longhorn