apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # OTel Collector
  - otel/otel.yaml

  # Promtail
  - promtail/release.yaml

  # Tracing (Jaeger)
  
  # Metrics (Prometheus)

  # Logging (Loki)
  - loki/repository.yaml
  - loki/release.yaml

  - namespace.yaml
