docker_necessary_packages:
  - curl
  - apt-transport-https
  - ca-certificates

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Set this variable to non-root user if you want to run docker as non-root user
docker_user: docker

# This is simply the name of the output script file
docker_rootless_installation_filename: dockerd-rootless-setuptool.sh
