---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-events
  namespace: argo-events
spec:
  interval: 1h
  chart:
    spec:
      chart: argo-events
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argo
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
