# Description: This task fetches the Talos image URL from the Talos Factory API.
---
- name: Fetch Image URL
  ansible.builtin.uri:
    method: POST
    url: https://factory.talos.dev/schematics
    body: "{{ lookup('ansible.builtin.file', 'bare-metal.yaml') }}"
    body_format: json
    status_code: 201
  register: talos_factory_image

- name: Set Talos Factory Image URL
  ansible.builtin.set_fact:
    talos_factory_image_id: "{{ talos_factory_image.json.id }}"
    talos_factory_image_url: "factory.talos.dev/installer/{{ talos_factory_image.json.id  }}:{{ talos_version }}"
