- name: Render kustomization.yaml
  ansible.builtin.template:
    src: templates/kustomization.yaml.j2
    dest: "{{ talos_cluster.working_dir }}/manifests/kustomization.yaml"
    mode: "0644"
  changed_when: true

- name: Wait for API Server
  ansible.builtin.wait_for:
    host: "{{ talos_cluster.endpoint }}"
    port: 6443
    delay: 10
    timeout: 300
  changed_when: false

- name: Apply Manifests
  ansible.builtin.command: >
    kubectl --kubeconfig={{ talos_cluster.working_dir }}/configs/kubeconfig apply -k {{ talos_cluster.working_dir }}/manifests
  changed_when: true
