-- Run this script to create a database and user for the REPLACE_ME application.
CREATE DATABASE REPLACE_ME;
CREATE USER REPLACE_ME WITH ENCRYPTED PASSWORD 'REPLACE_ME';
GRANT ALL ON DATABASE REPLACE_ME TO REPLACE_ME;

-- Run this in the REPLACE_ME database.
GRANT ALL ON SCHEMA public TO REPLACE_ME;


-- mysql
CREATE DATABASE CHANGE_ME;
CREATE USER 'CHANGE_ME'@'CHANGE_ME_IP' IDENTIFIED BY 'CHANGE_ME';
GRANT ALL PRIVILEGES ON CHANGE_ME.* TO 'CHANGE_ME'@'CHANGE_ME_IP';
