# This is a sample file on how to create a tls certificate in a namespace
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: minio
spec:
  secretName: minio-tls-secret
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - minio.prod.server.home
    - tenant.minio.prod.server.home
    - api.minio.prod.server.home
