---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio
spec:
  interval: 1h
  chart:
    spec:
      chart: operator
      version: "5.x.x"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio
  values:
    console:
      ingress:
        number: 9090
        enabled: true
        ingressClassName: istio
        host: minio.srv-lab.server.home
        tls:
          - secretName: minio-tls-secret
            hosts:
              - minio.srv-lab.server.home
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio
spec:
  interval: 1h
  chart:
    spec:
      chart: tenant
      version: "5.x.x"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio
  values:
    tenant:
      metrics:
        enabled: true
        port: 9000
        protocol: http
      certificate:
        requestAutoCert: false
      pools:
        - name: pool-0
          servers: 1 # standalone
          size: 10Gi
          storageClassName: longhorn
    ingress:
      api:
        enabled: true
        ingressClassName: istio
        host: api.minio.srv-lab.server.home
        tls:
          - secretName: minio-tls-secret
            hosts:
              - api.minio.srv-lab.server.home
      console:
        enabled: true
        ingressClassName: istio
        host: tenant.minio.srv-lab.server.home
        tls:
          - secretName: minio-tls-secret
            hosts:
              - tenant.minio.srv-lab.server.home
