---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: it-tools
  name: it-tools
  namespace: it-tools
secrets:
  - name: it-tools
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app.kubernetes.io/name: it-tools
  annotations:
    kubernetes.io/service-account.name: it-tools
