# Install Helm using the apt package manager
---
- name: Add helm gpg key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add helm repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm-stable-debian.list

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present
    update_cache: true
