---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-db-pvc
  namespace: mediawiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-single-replica
