---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-operator
        namespace: opentelemetry-operator
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-k8s
