---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-operator
  namespace: otel-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: otel-operator
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-k8s