version: "3.7"

services:
  dozzle:
    restart: always
    container_name: dozzle
    image: amir20/dozzle:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.rule=Host(`dozzle.srv-docker-1.server.io`)
      - traefik.http.routers.dozzle.tls=true
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - traefik_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik_default:
    external: true
