---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Helmchart
  - namespace.yaml
  - repository.yaml

  # Argo Workflows
  - workflows/cert.yaml
  - workflows/release.yaml
  - workflows/rbac.yaml
  - workflows/pg-cluster.yaml

  # Argo Events
  - events/release.yaml
