# Installs the packages listed in the variable `common_packages`

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true

- name: Install nfs-common
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: true
  when: inventory_hostname in groups['k8s_worker_nodes']
