apiVersion: v1
data:
  bookmarks.yaml: |
    - Developer:
      - Github:
        - abbr: GH
          href: https://github.com/kallepan
      - DockerHub:
        - abbr: DO
          href: https://hub.docker.com/u/kallepan
    - Social:
      - LinkedIn:
        - abbr: LI
          href: https://linkedin.com/kajeepan
    - Mail:
      - Gmail:
        - abbr: GM
          href: http://kajeepan.kandeepan@gmail.com
  docker.yaml: ''
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Infrastructure:
      - Pfsense:
          description: pfSense is a free and open source firewall and router that also
            features unified threat management, load balancing, multi WAN, and more.
          href: https://pfsense.server.io
          icon: pfsense.png
      - Proxmox:
          description: Proxmox VE is a complete open-source platform for enterprise virtualization.
          href: https://192.168.0.2:8006/
          icon: proxmox.png
      - KASM:
          description: Kasm Workspaces is a containerized application delivery platform
            that enables browser-based access to isolated applications and desktops
            running on Linux or Windows servers.
          href: https://srv-kasm-1.server.io/
          icon: kasm.png
    - Management:
      - Rancher:
          description: Rancher is a complete software stack for teams adopting containers.
          href: https://rancher.server.io
          icon: rancher.png
      - Portainer:
          description: Portainer is an open-source lightweight management UI which allows
            you to easily manage your Docker environments.
          href: https://portainer.srv-k8s.server.io/
          icon: portainer.png
      - Argo CD:
          description: Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes.
          href: https://argocd.srv-k8s.server.io
          icon: argocd.png
    - Storage:
      - Adminer:
          description: Adminer is a full-featured database management tool.
          href: http://srv-docker-2.server.io:8080/
          icon: adminer.png
      - MinIO:
          description: MinIO is a high performance object storage server.
          href: http://srv-docker-2.server.io:9002/browser/
          icon: minio.png
      - Nextcloud:
          description: Nextcloud is a suite of client-server software for creating and
            using file hosting services.
          href: https://nextcloud.srv-docker-1.server.io/
          icon: nextcloud.png
      - TrueNAS:
          description: TrueNAS is the world's #1 Open Source storage OS.
          href: https://nas-1.server.io/
          icon: truenas.png
      - Semaphore:
          description: Sempahore is a self-hosted ansible web UI.
          href: https://semaphore.srv-docker-1.server.io/
          icon: semaphore.png
    - Git:
      - GitLab:
          description: GitLab is a complete DevOps platform.
          href: https://gitlab.server.io/
          icon: gitlab.png
      - Registry:
          description: GitLab Container Registry is a secure and private registry for
            Docker images.
          href: https://gitlab.server.io:5050/
          icon: gitlab.png
      - Pages:
          description: GitLab Pages is a static site hosting service. This is an example
            of a static site hosted on GitLab Pages.
          href: https://pages.server.io/landing/public/index.html
          icon: gitlab.png
    - Monitoring:
      - Traefik Kubernetes Production:
          description: Traefik is a modern HTTP reverse proxy and load balancer.
          href: https://traefik.srv-k8s.server.io/dashboard/
          icon: traefik.png
      - Traefik Kubernetes Staging:
          description: Traefik is a modern HTTP reverse proxy and load balancer.
          href: https://traefik.srv-k3s.server.io/dashboard/
          icon: traefik.png
      - Traefik Docker:
          description: Traefik is a modern HTTP reverse proxy and load balancer.
          href: https://traefik.srv-docker-1.server.io/
          icon: traefik.png
      - Uptime Kuma:
          description: Uptime Kuma is a fancy self-hosted monitoring tool.
          href: https://uptime.srv-k8s.server.io/
          icon: uptime-kuma.png
      - Dozzle:
          description: Dozzle is a simple container log viewer for Docker.
          href: https://dozzle.srv-docker-1.server.io/
          icon: dozzle.png
    - Docs:
      - Wiki:
          description: Mediawiki is a free and open-source wiki software.
          href: https://wiki.srv-docker-1.server.io/
          icon: mediawiki.png
      - It-Tools:
          description: It-tools is a collection of tools useful for IT professionals.
          href: https://it-tools.srv-docker-1.server.io/
          icon: it-tools.png
    - Security:
      - Keycloak:
          description: Keycloak is an open source identity and access management solution.
          href: https://keycloak.srv-docker-1.server.io/
          icon: keycloak.png
      - Hashicorp Vault:
          description: Vault is a tool for securely accessing secrets.
          href: https://vault.srv-k8s.server.io/
          icon: vault.png
    - Misc:
      - MeTube:
          description: MeTube is a self-hosted youtube downloader.
          href: https://metube.srv-docker-1.server.io/
          icon: metube.png
      - Mealie:
          description: Mealie is a self-hosted recipe manager and meal planner.
          href: https://mealie.srv-docker-1.server.io
          icon: mealie.png
  custom.css: ''
  custom.js: ''
  settings.yaml: |
    title: HomeLab
    base: https://homepage.srv-k8s.server.io/
    showStats: false
    theme: dark
    color: slate
    quicklaunch:
      searchDescriptions: false
      hideInternetSearch: false
      hideVisitURL: false
    layout:
      Infrastructure:
        header: true
        icon: netboot.png
        style: row
        columns: 4
      Management:
        header: true
        icon: docker.png
        style: row
        columns: 4
      Storage:
        header: true
        icon: baserow.png
        style: row
        columns: 4
      Monitoring:
        header: true
        icon: bazarr.png
        style: row
        columns: 4
      Docs:
        header: true
        icon: coder.png
        style: row
        columns: 4
      Git:
        header: true
        icon: git.png
        style: row
        columns: 4
      Security:
        header: true
        icon: hashicorp.png
        style: row
        columns: 4
      Misc:
        header: true
        icon: selfhosted.png
        style: row
        columns: 4
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - datetime:
        format:
          timeStyle: short
        text_size: x1
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: homepage
  name: homepage
  namespace: homepage
