---
# I have created this Deployment in order to cover all of the use cases of opentelemetry in which only one instance for logs, metrics and traces is needed
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-deployment
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: observability
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: otel/opentelemetry-collector-k8s

    mode: deployment
    replicaCount: 1

    presets:
      kubernetesEvents:
        enabled: true

    config:
      extensions:
        health_check:
          endpoint: ${env:MY_POD_IP}:13133

      receivers:
        k8sobjects:
          objects:
            - name: events
              mode: pull
              group: events.k8s.io
              interval: 1m

      processors:
        resource:
          attributes:
            - key: service.name
              value: "kube-events"
              action: upsert
        transform:
          error_mode: ignore
          log_statements:
            - context: log
              statements:
                - keep_keys(body, ["type", "action", "eventTime", "reason", "regarding", "reportingController", "note", "series", "metadata", "deprecatedFirstTimestamp", "deprecatedLastTimestamp"])

      exporters:
        debug: {}
        otlphttp/logs:
          endpoint: http://loki-distributor.observability.svc.cluster.local:3100/otlp
          tls:
            insecure: true

      service:
        pipelines:
          logs:
            exporters:
              - otlphttp/logs
            processors:
              - resource
            receivers:
              - k8sobjects
