apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mattermost-cert
  namespace: istio-system
spec:
  secretName: mattermost-tls-secret
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - mattermost.prod.server.home
