apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
  namespace: mattermost
spec:
  size: 100users
  image: mattermost/mattermost-team-edition
  ingress:
    enabled: false
  mattermostEnv:
    - name: MM_SERVICESETTINGS_ALLOWCORSFROM
      value: "*"
  podExtensions:
    initContainers:
      - name: init
        image: busybox
        command: ["sh", "-c"]
        args:
          - |
            chmod -R 777 /mattermost/data
        volumeMounts:
          - name: mattermost-data
            mountPath: /mattermost/data
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
  database:
    external:
      secret: mattermost-database-secret
  fileStore:
    externalVolume:
      volumeClaimName: mattermost-data
  volumeMounts:
    - name: ca-secret
      mountPath: /etc/ssl/certs/homelab_ca.crt
      subPath: homelab_ca.crt
      readOnly: true
  volumes:
    - name: ca-secret
      secret:
        items:
          - key: homelab_ca.crt
            path: homelab_ca.crt
        secretName: homelab-ca
