---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/flux/infrastructure/controllers
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-crds
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/flux/infrastructure/crds
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-crds
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/flux/infrastructure/configs
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /spec/addresses
          value:
            - 10.0.255.128-10.0.255.254
      target:
        kind: IPAddressPool
        name: main-pool
    - patch: |
        - op: replace
          path: /spec/dnsNames
          value:
            - '*.srv-k3s.server.io'
      target:
        kind: Certificate
        name: traefik-cert
        namespace: traefik-system