apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - istio-base/release.yaml
  - istiod/release.yaml
  - istio-ingressgateway/release.yaml
  - istio-cni/release.yaml
  - ztunnel/release.yaml

  - telemetry.yaml
