apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: otel-telemetry
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100
      customTags:
        cluster:
          literal:
            value: "production"
