apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/metallb-system
  - ../base/observability
patches:
  - patch: |
      - op: add
        path: /spec/addresses/-
        value: 10.40.0.10/32
    target:
      kind: IPAddressPool
      name: default-ippool
      namespace: metallb-system

