version: '3.8'

services:
  traefik:
    restart: always
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "2222:2222"
      # (Optional) Expose Dashboard
      # - "8080:8080"  # Don't do this in production!
    volumes:
      - /srv/traefik/config:/etc/traefik
      - traefik-ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_default
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.CHANGEME.rule=Host(`traefik.srv-docker-1.server.io`)
      - traefik.http.routers.CHANGEME.tls=true
      - traefik.http.services.CHANGEME.loadbalancer.server.port=8080

networks:
  traefik_default:
    external: true

volumes:
  traefik-ssl-certs:
    driver: local
