---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: ztunnel
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values: {}
