---
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx
spec:
  image: emqx:5
  coreTemplate:
    spec:
      replicas: 1
    metadata:
      labels:
        app: emqx
