# Install kubernetes tools

- name: Delete old kubernetes GPG key
  become: true
  become_user: root
  ansible.builtin.file:
    path: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    state: absent
    mode: "0644"
  tags: [kubernetes, kubeadm]

- name: Download kubernetes GPG key
  become: true
  become_user: root
  ansible.builtin.get_url:
    force: true
    url: "{{ kubernetes_key_url }}"
    dest: /tmp/kubernetes-archive-keyring.gpg_amored
    mode: "0644"
  tags: [kubernetes, kubeadm]

- name: Install kubernetes GPG key
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      cat /tmp/kubernetes-archive-keyring.gpg_amored | gpg --dearmor --yes -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    executable: /bin/bash
  tags: [kubernetes, kubeadm]
  register: kubernetes_key_output
  changed_when: kubernetes_key_output.stdout != 0

- name: Delete old kubernetes repository file
  become: true
  become_user: root
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent
  tags: [kubernetes, kubeadm]

- name: Add new Kubernetes apt repository
  become: true
  become_user: root
  ansible.builtin.apt_repository:
    filename: kubernetes
    repo: "{{ kubernetes_apt_repository }}"
    state: present
    update_cache: true
  tags: [kubernetes, kubeadm]

- name: Install kubeadm, kubelet and kubectl
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - kubeadm
    - kubelet
    - kubectl
  tags: [kubernetes, kubeadm]

- name: Hold kubeadm, kubelet and kubectl
  become: true
  become_user: root
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubeadm
    - kubelet
    - kubectl
  tags: [kubernetes, kubeadm]
