# Disable swap

- name: Check if /etc/fstab exists
  become: true
  become_user: root
  ansible.builtin.stat:
    path: "/etc/fstab"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: fstab_file
  tags: [kubernetes, swapoff]

- name: Remove swapfile from /etc/fstab
  become: true
  become_user: root
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
  when: fstab_file.stat.exists
  tags: [kubernetes, swapoff]

- name: Mask swap.target (persist swapoff)
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: swap.target
    masked: true
  tags: [kubernetes, swapoff]

- name: Disable swap
  become: true
  become_user: root
  ansible.builtin.command: /sbin/swapoff -a
  tags: [kubernetes, swapoff]
  register: swapoff_output
  changed_when: swapoff_output.stdout != 0
