---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-namespaces
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/core/infrastructure/namespaces
  force: true
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-core
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/core/infrastructure/core
  force: true
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure-namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-configs
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/core/infrastructure/configs
  force: true
  prune: true
  dependsOn:
    - name: infrastructure-core
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-operators
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/core/infrastructure/operators
  force: true
  prune: true
  dependsOn:
    - name: infrastructure-core
