---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: promtail
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    config:
      clients:
        - url: http://opentelemetry-collector.observability.svc.cluster.local:3500/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}
