---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mattermost-operator
  namespace: mattermost-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: mattermost-operator
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: mattermost
        namespace: mattermost-operator
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
