---
- name: Start Docker
  ansible.builtin.systemd:
    scope: user
    name: docker
    state: started
    enabled: true
  become: true
  become_user: "{{ docker_user }}"
  when: docker_user != 'root'

- name: Restart Docker
  ansible.builtin.systemd:
    scope: user
    name: docker
    state: restarted
  become: true
  become_user: "{{ docker_user }}"
  when: docker_user != 'root'
