# Shutdown all nodes
---
- name: Shutdown
  hosts: k8s_cluster
  become: true
  tasks:
    - name: Shutdown all nodes
      ansible.builtin.command: shutdown -h now
      async: 0
      poll: 0
      failed_when: false
      changed_when: false
