apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/metallb-system
  - ../base/gitlab-runner
  - ../base/homepage
  - ../base/it-tools
  - ../base/istio-system
  - ../base/monitoring
  - ../base/mattermost
  - ../base/nextcloud
patches:
  - patch: |
      - op: add
        path: /spec/addresses/-
        value: 10.30.0.10/32
    target:
      kind: IPAddressPool
      name: default-ippool
      namespace: metallb-system
