---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - default-ippool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ippool
  namespace: metallb-system
spec:
  addresses:
    - 10.10.0.10/32
