---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: argo
spec:
  interval: 1h
  chart:
    spec:
      chart: argo-cd
      version: "7.x.x"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argo
  values:
    configs:
      params:
        server.insecure: true
    server:
      extraArgs:
        - --insecure
      ingress:
        enabled: true
        hosts:
          - host: argocd.prod.server.home
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: traefik
        tls:
          - hosts:
              - argocd.prod.server.home
            secretName: argocd-tls-secret
