apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/cnpg-operator
  - ../base/gitlab-operator
  - ../base/istio-system
  - ../base/keycloak-operator
  # - ../base/metallb-system
  - ../base/metrics-server
  - ../base/openebs
