apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/cnpg-operator
  - ../base/gitlab-operator
  - ../base/istio-system
  - ../base/keycloak-operator
  - ../base/metallb-system
  - ../base/metrics-server
  - ../base/openebs
patches:
  - patch: |
      - op: replace
        path: /spec/values/meshID
        value: core-cluster-mesh
    target:
      kind: HelmRelease
      name: istiod
      namespace: istio-system
  - patch: |
      - op: replace
        path: /spec/values/service/loadBalancerIP
        value: 10.10.0.10
    target:
      kind: HelmRelease
      name: istio-ingressgateway
      namespace: istio-system
