---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - capacitor
  - portainer
  - monitoring
  - it-tools
  - homepage
  - argo
  - nextcloud
  - keycloak
  - minio
  - kiali
  - jaeger
  - gitlab
  - gitlab-runner
  - kyverno
  - mattermost
  - oauth2-proxy
  - web-example
