#
- name: Apply sysctl settings
  become: true
  become_user: root
  ansible.builtin.command: /sbin/sysctl --system
  tags: [kubernetes, sysctl]
  register: sysctl_output
  changed_when: sysctl_output.stdout != 0
