apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/istio-system
  - ../base/jaeger-operator
  - ../base/kiali-operator
  - ../base/metallb-system
patches:
  - patch: |
      - op: replace
        path: /spec/values/service/loadBalancerIP
        value: 10.40.0.10
    target:
      kind: HelmRelease
      name: istio-ingressgateway
      namespace: istio-system
  - patch: |
      - op: add
        path: /spec/values/meshConfig/extensionProviders/-
        value:
          name: "otel-tracing"
          opentelemetry:
            port: 4317
            service: "otel-daemonset-collector.observability.svc.cluster.local"
            resource_detectors:
              environment: {}
    target:
      kind: HelmRelease
      name: istiod
      namespace: istio-system
  - patch: |
      - op: replace
        path: /spec/values/meshConfig/enableTracing
        value: true
    target:
      kind: HelmRelease
      name: istiod
      namespace: istio-system
  - patch: |
      apiVersion: telemetry.istio.io/v1
      kind: Telemetry
      metadata:
        name: otel-telemetry
        namespace: istio-system
      $patch: delete
