---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tools-ingress
  namespace: it-tools
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`it-tools.prod.server.home`)
      priority: 10
      services:
        - name: tools-svc
          port: 80
  tls:
    secretName: tools-tls
