apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
  namespace: istio-system

spec:
  secretName: homepage-tls-secret
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - homepage.prod.server.home
