---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1h
  timeout: 30m
  chart:
    spec:
      chart: metallb
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    speaker:
      tolerateMaster: false
