---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 1h
  targetNamespace: keycloak
  sourceRef:
    kind: GitRepository
    name: keycloak
  path: ./kubernetes
  prune: true
  timeout: 5m
