---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: knative-operator
  namespace: knative-operator
spec:
  interval: 1h
  url: https://github.com/knative/operator
  ref:
    # https://github.com/knative/operator/releases/
    tag: "1.16.0"
