apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-operator.yaml
  - keycloak.yaml
  - kube-prometheus-stack.yaml
  - mattermost-operator.yaml
  - jaeger-operator.yaml
