---
apiVersion: v1
kind: Namespace
metadata:
  name: mattermost-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mattermost
  namespace: mattermost-operator
spec:
  interval: 1h
  url: https://helm.mattermost.com
  timeout: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mattermost-operator
  namespace: mattermost-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: mattermost-operator
      version: "1.x.x"
      sourceRef:
        kind: HelmRepository
        name: mattermost
        namespace: mattermost-operator
