---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 1h
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: traefik
      version: "32.x.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-system
  values:
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
          - websecure
        matchRule: Host(`traefik.prod.server.home`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
        tls:
          secretName: traefik-tls
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
    logs:
      general:
        level: ERROR
    ports:
      ssh:
        expose:
          default: true
        exposedPort: 22
        port: 2222
        protocol: TCP
      metrics:
        expose:
          default: false
        exposedPort: 9100
        port: 9100
        protocol: TCP
      traefik:
        expose:
          default: true
        exposedPort: 9000
        port: 9000
        protocol: TCP
      web:
        expose:
          default: true
        exposedPort: 80
        port: 8000
        protocol: TCP
      websecure:
        expose:
          default: true
        exposedPort: 443
        http3:
          enabled: false
        middlewares: []
        port: 8443
        protocol: TCP
        tls:
          certResolver: ""
          domains: []
          enabled: true
          options: ""
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.0.255.1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: traefik-system
spec:
  secretName: traefik-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - traefik.prod.server.home
