# This is a sample file on how to create a tls certificate in a namespace
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-workflows-tls
  namespace: istio-system
spec:
  secretName: argo-workflows-tls-secret
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - argo-workflows.prod.server.home
