# Contains a collection of bootstrap apps to install on the docker host
---
# Registers the user id
- name: Register user id
  ansible.builtin.command:
    cmd: id -u
  register: user_id
  become: true
  become_user: "{{ docker_user }}"
  changed_when: true

- name: Check if Portainer Agent is installed
  ansible.builtin.command:
    cmd: >
      /home/{{ docker_user }}/bin/docker ps -f name=portainer_agent
  environment:
    DOCKER_HOST: unix:///run/user/{{ user_id.stdout }}/docker.sock
  register: portainer_agent_installed
  become_user: "{{ docker_user }}"
  become: true
  changed_when: false

# Use that user id to install Portainer Agent
- name: Install Portainer Agent on Docker
  ansible.builtin.command:
    cmd: >
      /home/{{ docker_user }}/bin/docker run -d
      -p {{ docker_portainer_agent_port }}:9001
      --name portainer_agent
      --restart=always
      -v /run/user/{{ user_id.stdout }}/docker.sock:/var/run/docker.sock:ro
      -v /home/{{ docker_user }}/volumes:/var/lib/docker/volumes
      portainer/agent:{{ docker_portainer_agent_version }}
  environment:
    DOCKER_HOST: unix:///run/user/{{ user_id.stdout }}/docker.sock
  become_user: "{{ docker_user }}"
  become: true
  when: docker_install_portainer_agent and portainer_agent_installed.stdout_lines == 0
  changed_when: false
  tags: portainer_agent
