# Description: This Ansible task installs Rootless Docker on a remote machine.
---
- name: Download Rootless Docker installer
  ansible.builtin.get_url:
    url: https://get.docker.com/rootless
    dest: /home/{{ docker_user }}/{{ docker_rootless_installation_filename }}
    mode: "0755"
  become: true
  become_user: "{{ docker_user }}"

- name: Remove old installation
  ansible.builtin.file:
    path: /home/{{ docker_user }}/bin
    state: absent
  become: true
  become_user: "{{ docker_user }}"

- name: Run Rootless Docker installer
  ansible.builtin.command:
    cmd: bash ~/{{ docker_rootless_installation_filename }}
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ docker_user_uid | default(3000) }}"
  register: installer_output
  become: true
  become_user: "{{ docker_user }}"
  changed_when: true # Always run the installer as we always want the latest version

- name: Check if Docker is installed
  ansible.builtin.assert:
    that:
      - "'Installed docker.service successfully.' in installer_output.stdout"
    fail_msg: "Docker installation failed. Logs: {{ installer_output.stdout }}"

  notify: Start Docker

- name: Create a plugin directory if it doesn't exist
  ansible.builtin.file:
    path: ~/.docker/cli-plugins
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ docker_user }}"

- name: Download Docker Compose plugin
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: ~/.docker/cli-plugins/docker-compose
    mode: "0755"
  become: true
  become_user: "{{ docker_user }}"

- name: Add DOCKER_HOST to .bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ docker_user }}/.bashrc
    line: "export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock"
  become: true
  become_user: "{{ docker_user }}"

- name: Add Docker bin to PATH in .bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ docker_user }}/.bashrc
    line: "export PATH=$PATH:/home/{{ docker_user }}/bin"
  become: true
  become_user: "{{ docker_user }}"

- name: Add .docker/cli-plugins to PATH in .bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ docker_user }}/.bashrc
    line: "export PATH=$PATH:/home/{{ docker_user }}/.docker/cli-plugins"
  become: true
  become_user: "{{ docker_user }}"
