---
- name: Do preflight checks
  ansible.builtin.include_tasks: preflight.yml

- name: Install Docker as Root
  ansible.builtin.include_tasks: install_root_docker.yml
  when: docker_user == 'root'

- name: Install Docker as Non-Root
  ansible.builtin.include_tasks: install_rootless_docker.yml
  when: docker_user != 'root'

- name: Do Postflight lulz
  ansible.builtin.include_tasks: postflight.yml
