# Description: This task is used to set the capability to allow the usage of priviledged ports by the rootlesskit binary.
---
- name: Allow the usage of priviledged ports
  ansible.builtin.command:
    cmd: setcap cap_net_bind_service=ep /home/{{ docker_user }}/bin/rootlesskit
  become: true
  become_user: root
  notify: Restart Docker
  when: docker_user != 'root'
  changed_when: true # Always set the capability just in case the binary was updated
