apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/istio-system
  - ../base/metallb-system
  - ../base/cert-manager
  - ../base/gitlab
  - ../base/keycloak
  - ../base/monitoring
  - ../base/vault
patches:
  - patch: |
      - op: replace
        path: /spec/values/service/loadBalancerIP
        value: 10.10.0.10
    target:
      kind: HelmRelease
      name: istio-ingressgateway
      namespace: istio-system
  - patch: |
      - op: add
        path: /spec/addresses/-
        value: 10.10.0.10/32
    target:
      kind: IPAddressPool
      name: default-ippool
      namespace: metallb-system
