apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/gitlab
  - ../base/gitlab-runner
  - ../base/istio-system
  - ../base/keycloak
  - ../base/metallb-system
  - ../base/monitoring
  - ../base/privileged-runner
  - ../base/vault
patches:
  - patch: |
      - op: add
        path: /spec/addresses/-
        value: 10.10.0.10/32
    target:
      kind: IPAddressPool
      name: default-ippool
      namespace: metallb-system
  - patch: |
      - op: replace
        path: /spec/values/alertmanager/alertmanagerSpec/externalUrl
        value: https://mgmt.infra.server.home/k8s/clusters/c-m4mgb/api/v1/namespaces/monitoring/services/http:prometheus-kube-prometheus-alertmanager:9093/proxy/
    target:
      kind: HelmRelease
      name: prometheus
      namespace: monitoring
