apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/dashboards
  - ../base/gitlab
  - ../base/gitlab-runner
  - ../base/keycloak
  - ../base/metallb-system
  - ../base/privileged-runner
  - ../base/vault
patches:
  - patch: |
      - op: add
        path: /spec/addresses/-
        value: 10.10.0.10/32
    target:
      kind: IPAddressPool
      name: default-ippool
      namespace: metallb-system
