apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-sigs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: kubernetes-sigs
spec:
  interval: 1h
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: "v1.2.0"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: kubernetes-sigs
spec:
  interval: 1h
  targetNamespace: kubernetes-sigs
  sourceRef:
    kind: GitRepository
    name: gateway-api
  path: ./config/crd
  prune: true
  timeout: 5m
