---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  timeout: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.x.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  values:
    # Hint: Do not forget to add the labels to the nodes
    defaultSettings:
      systemManagedComponentsNodeSelector: "kubernetes.io/role:worker"
    longhornManager:
      nodeSelector:
        kubernetes.io/role: "worker"
        kubernetes.io/storage: "longhorn"
    longhornDriver:
      nodeSelector:
        kubernetes.io/role: "worker"
        kubernetes.io/storage: "longhorn"
    longhornUI:
      nodeSelector:
        kubernetes.io/role: "worker"
        kubernetes.io/storage: "longhorn"
