# This file contains various secrets that are used by GitLab. The secrets are:
apiVersion: v1
kind: Secret
metadata:
  name: homelab-ca
  namespace: gitlab
type: Opaque
data:
  homelab-ca.crt: CHANGEME