apiVersion: v1
data:
  bookmarks.yaml: |
    - Developer:
      - Github:
        - abbr: GH
          href: https://github.com/kallepan
      - DockerHub:
        - abbr: DO
          href: https://hub.docker.com/u/kallepan
    - Social:
      - LinkedIn:
        - abbr: LI
          href: https://linkedin.com/kajeepan
    - Mail:
      - Gmail:
        - abbr: GM
          href: http://kajeepan.kandeepan@gmail.com
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Networking:
      - WireGuard:
          description: WireGuard is a free and open-source software application and
            communication protocol that implements virtual private network techniques
            to create secure point-to-point connections in routed or bridged configurations.
          href: http://192.168.0.4:51820
          icon: wireguard.png
    - Infrastructure:
      - Proxmox:
          description: Proxmox VE is a complete open-source platform for enterprise virtualization.
          href: https://192.168.0.2:8006/
          icon: proxmox.png
      - Rancher:
          description: Rancher is a complete software stack for teams adopting containers.
          href: https://srv-rancher.server.home
          icon: rancher.png
      - KASM:
          description: Kasm Workspaces is a containerized application delivery platform
            that enables browser-based access to isolated applications and desktops
            running on Linux or Windows servers.
          href: https://srv-kasm.server.home/
          icon: kasm.png
    - Management:
      - Portainer:
          description: Portainer is an open-source lightweight management UI which allows
            you to easily manage your Docker environments.
          href: https://portainer.prod.server.home/
          icon: portainer.png
      - Netboot XYZ:
          description: Netboot.xyz is a way to PXE boot various operating system installers
            or utilities from one place within the BIOS without the need of having to
            go retrieve the media to run the tool.
          href: https://server.home/
          icon: netboot.png
      - Traefik Kubernetes Production:
          description: Traefik is a modern HTTP reverse proxy and load balancer.
          href: https://traefik.prod.server.home/dashboard/
          icon: traefik.png
      - Traefik Docker:
          description: Traefik is a modern HTTP reverse proxy and load balancer.
          href: https://traefik.srv-core.server.home/dashboard/
          icon: traefik.png
    - Storage:
      - Nextcloud:
          description: Nextcloud is a suite of client-server software for creating and
            using file hosting services.
          href: https://nextcloud.prod.server.home/
          icon: nextcloud.png
      - Minio:
          description: MinIO is a high performance, distributed object storage system.
          href: https://tenant.minio.prod.server.home/
          icon: minio.png
    - GitOps:
      - GitLab:
          description: GitLab is a complete DevOps platform.
          href: https://gitlab.prod.server.home/users/sign_in?auto_sign_in=false
          icon: gitlab.png
      - Argo CD:
          description: Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes.
          href: https://argocd.prod.server.home
          icon: argocd.png
      - Argo Workflows:
          description: Argo Workflows is an open source container-native workflow engine
            for orchestrating parallel jobs on Kubernetes.
          href: https://argo-workflows.prod.server.home
          icon: argocd.png
      - Flux CI/CD:
          description: Flux is a tool that automatically ensures that the state of a
            cluster matches the config in git.
          href: https://flux.prod.server.home/
          icon: flux-cd.png
    - Monitoring & Logging:
      - Wazuh:
          description: Wazuh is a free, open-source and enterprise-ready security monitoring
            solution for threat detection, integrity monitoring, incident response
            and compliance.
          href: https://wazuh.srv-core.server.home/
          icon: wazuh.png
      - Grafana:
          description: Grafana is the open source analytics & monitoring solution for
            every database.
          href: https://monitoring.prod.server.home/
          icon: grafana.png
    - Docs:
      - Wiki:
          description: Mediawiki is a free and open-source wiki software.
          href: https://wiki.prod.server.home/
          icon: mediawiki.png
      - It-Tools:
          description: It-tools is a collection of tools useful for IT professionals.
          href: https://it-tools.prod.server.home/
          icon: it-tools.png
    - Security and Identity:
      - Keycloak:
          description: Keycloak is an open source identity and access management solution.
          href: https://sso.prod.server.home/
          icon: keycloak.png
  custom.css: ""
  custom.js: ""
  settings.yaml: |
    title: HomeLab
    base: https://homepage.prod.server.home/
    showStats: false
    theme: dark
    color: slate
    headerStyle: boxed
    quicklaunch:
      searchDescriptions: false
      hideInternetSearch: false
      hideVisitURL: false
    layout:
      Networking:
        icon: mdi-network
      Infrastructure:
        icon: mdi-server
      Management:
        icon: mdi-auto-fix
      Storage:
        icon: mdi-database
      GitOps:
        icon: mdi-git
      Monitoring & Logging:
        icon: mdi-format-list-checks
      Docs:
        icon: mdi-file-document
      Security and Identity:
        icon: mdi-security
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - datetime:
        format:
          timeStyle: short
        text_size: x1
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage-production
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: homepage
    app.kubernetes.io/managed-by: flux
  name: homepage
  namespace: homepage
