apiVersion: v1
data:
  bookmarks.yaml: |
    - Developer:
      - Github:
        - abbr: GH
          href: https://github.com/kallepan
      - DockerHub:
        - abbr: DO
          href: https://hub.docker.com/u/kallepan
    - Social:
      - LinkedIn:
        - abbr: LI
          href: https://linkedin.com/kajeepan
    - Mail:
      - Gmail:
        - abbr: GM
          href: http://kajeepan.kandeepan@gmail.com
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Networking:
      - WireGuard:
          description: WireGuard is a free and open-source software application and
            communication protocol that implements virtual private network techniques
            to create secure point-to-point connections in routed or bridged configurations.
          href: http://192.168.0.4:51820
          icon: wireguard.png
    - Infrastructure:
      - Proxmox:
          description: Proxmox VE is a complete open-source platform for enterprise virtualization.
          href: https://192.168.0.2:8006/
          icon: proxmox.png
      - Harvester:
          description: Harvester is an open-source hyperconverged infrastructure (HCI)
            software built using Kubernetes.
          href: https://srv-harvester.server.home/
          icon: harvester.png
    - Management:
      - Rancher:
          description: Rancher is a complete software stack for teams adopting containers.
          href: https://srv-rancher.server.home
          icon: rancher.png
      - Portainer:
          description: Portainer is an open-source lightweight management UI which allows
            you to easily manage your Docker environments.
          href: https://portainer.srv-lab.server.home/
          icon: portainer.png
      - Traefik Docker:
          description: Traefik is a modern HTTP reverse proxy and load balancer.
          href: https://traefik.srv-core.server.home/dashboard/
          icon: traefik.png
      - Kiali:
          description: Kiali is an observability console for Istio with service mesh
            configuration capabilities.
          href: https://srv-rancher.server.home/k8s/clusters/c-m-dkwj54c7/api/v1/namespaces/istio-system/services/http:kiali:20001/proxy/kiali/console/overview?duration=60&refresh=60000
          icon: traefik-proxy.png
    - Storage:
      - Nextcloud:
          description: Nextcloud is a suite of client-server software for creating and
            using file hosting services.
          href: https://nextcloud.srv-lab.server.home/
          icon: nextcloud.png
      - Minio:
          description: MinIO is a high performance, distributed object storage system.
          href: https://tenant.minio.srv-lab.server.home/
          icon: minio.png
      - Longhorn:
          description: Longhorn is a distributed block storage system for Kubernetes.
          href: https://srv-rancher.server.home/k8s/clusters/c-m-dkwj54c7/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/#/volume
          icon: longhorn.png
      - Harbor:
          description: Harbor is an open source trusted cloud native registry project
            that stores, signs, and scans content.
          href: https://harbor.srv-lab.server.home/
          icon: harbor.png
    - GitOps:
      - GitLab:
          description: GitLab is a complete DevOps platform.
          href: https://gitlab.srv-lab.server.home/users/sign_in?auto_sign_in=false
          icon: gitlab.png
      - Argo CD:
          description: Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes.
          href: https://argocd.srv-lab.server.home
          icon: argocd.png
      - Argo Workflows:
          description: Argo Workflows is an open source container-native workflow engine
            for orchestrating parallel jobs on Kubernetes.
          href: https://argo-workflows.srv-lab.server.home
          icon: argocd.png
      - Flux CI/CD:
          description: Flux is a tool that automatically ensures that the state of a
            cluster matches the config in git.
          href: https://flux.srv-lab.server.home/
          icon: flux-cd.png
    - Monitoring & Logging:
      - Wazuh:
          description: Wazuh is a free, open-source and enterprise-ready security monitoring
            solution for threat detection, integrity monitoring, incident response
            and compliance.
          href: https://srv-wazuh.server.home/
          icon: wazuh.png
      - Grafana:
          description: Grafana is the open source analytics & monitoring solution for
            every database.
          href: https://monitoring.srv-lab.server.home/
          icon: grafana.png
    - Docs:
      - It-Tools:
          description: It-tools is a collection of tools useful for IT professionals.
          href: https://it-tools.srv-lab.server.home/
          icon: it-tools.png
      - Mattermost:
          description: Mattermost is an open source, self-hosted Slack-alternative.
          href: https://mattermost.srv-lab.server.home/
          icon: mattermost.png
    - Security and Identity:
      - Keycloak:
          description: Keycloak is an open source identity and access management solution.
          href: https://sso.srv-lab.server.home/
          icon: keycloak.png
      - OAuth2 Proxy:
          description: OAuth2 Proxy example.
          href: https://example.srv-lab.server.home/
          icon: oauth2-proxy.png

  custom.css: ""
  custom.js: ""
  settings.yaml: |
    title: HomeLab
    base: https://homepage.srv-lab.server.home/
    showStats: false
    theme: dark
    color: slate
    headerStyle: boxed
    quicklaunch:
      searchDescriptions: false
      hideInternetSearch: false
      hideVisitURL: false
    layout:
      Networking:
        icon: mdi-network
      Infrastructure:
        icon: mdi-server
      Management:
        icon: mdi-auto-fix
      Storage:
        icon: mdi-database
      GitOps:
        icon: mdi-git
      Monitoring & Logging:
        icon: mdi-format-list-checks
      Docs:
        icon: mdi-file-document
      Security and Identity:
        icon: mdi-security
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - datetime:
        format:
          timeStyle: short
        text_size: x1
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage-production
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: homepage
    app.kubernetes.io/managed-by: flux
  name: homepage
  namespace: homepage
