version: '3.8'

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    volumes:
      - ./data:/var/www/html
    environment:
      - POSTGRES_PASSWORD=CHANGEME
      - POSTGRES_DATABASE=CHANGEME
      - POSTGRES_USER=CHANGEME
      - POSTGRES_DB=10.0.0.8:5432
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.srv-0.server.home`)
      - traefik.http.routers.nextcloud.tls=true
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
