---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: istiod
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
