---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 30m
  chart:
    spec:
      chart: gatus
      version: "3.x.x"
      sourceRef:
        kind: HelmRepository
        name: gatus
        namespace: gatus
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      size: 200Mi
      accessModes: [ReadWriteOnce]
      storageClassName: longhorn
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts: ["gatus.srv-k8s.server.io"]
      tls:
        - secretName: gatus-tls
          hosts:
            - gatus.srv-k8s.server.io
    config:
      storage:
        type: sqlite
        path: /data/data.db
      endpoints:
        - name: Rancher
          url: https://rancher.srv-k8s.server.io
          client:
            insecure: true
            timeout: 5s
          conditions:
            - "[STATUS] == 200"
        - name: GitLab
          url: https://gitlab.srv-k8s.server.io
          client:
            insecure: true
            timeout: 5s
          conditions:
            - "[STATUS] == 200"
        - name: Gatus
          url: https://gatus.srv-k8s.server.io
          client:
            insecure: true
            timeout: 5s
          conditions:
            - "[STATUS] == 200"
      ui:
        title: Gatus
        description: "Gatus is a simple service health checker."
