apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-example-cert
  namespace: istio-system
spec:
  secretName: web-example-tls
  dnsNames:
    - oauth2.prod.server.home
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
