---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert.yaml
  - deployment.yaml
  - service.yaml
  - istio.yaml
commonLabels:
  app.kubernetes.io/name: oauth2-proxy
  app.kubernetes.io/instance: oauth2-proxy-production
  app.kubernetes.io/version: "1.0"
  app.kubernetes.io/component: example
  app.kubernetes.io/part-of: oauth2-proxy
  app.kubernetes.io/managed-by: flux
