---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: argo
spec:
  interval: 1h
  chart:
    spec:
      chart: argo-workflows
      version: "x"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argo
  values:
    workflow:
      serviceAccount:
        create: true
        name: argo-workflows
      rbac:
        create: true
    controller:
      workflowNamespaces:
        - workflows
    server:
      ingress:
        enabled: true
        ingressClassName: istio
        hosts:
          - argo-workflows.srv-lab.server.home
        tls:
          - secretName: argo-workflows-tls-secret
            hosts:
              - argo-workflows.srv-lab.server.home
      sso:
        enabled: true
        issuer: https://sso.srv-lab.server.home
        clientId:
          name: argo-workflows-oauth-creds
          key: client_id
        clientSecret:
          name: argo-workflows-oauth-creds
          key: client_secret
        redirectUrl: https://argo-workflows.srv-lab.server.home/oauth2/callback
